// maizuo_vue/src/app/views/header.vue
<template>
	<header>
		<div id="nav_bth" @click="pdMenu">
			<img src="src/images/icon/我的订单.png">
		</div>
		<span class="title">{{$store.state.headerName}}</span>
		<div id="mine_bth" @click="toMine">
			<img src="src/images/icon/我的聚划算.png">
		</div><div class="city">
		<span @click="toCitys">{{$store.state.city}}</span>
			<img src="src/images/icon/向下箭头.png">
		</div>
	</header>
</template>
<script type="text/javascript">
	export default {
		name:'header',
		data(){
			return {

			}
		},
		methods:{
			pdMenu(){
				this.$store.dispatch('changeMenu');
			},
			toMine(){
				window.router.push('/mine');
			},
			toCitys(){
				window.router.push('/citys');
			}
		}
	}


</script>

// maizuo_react/src/app/header/header.jsx
import React,{Component} from 'react' ;
import {browserHistory} from 'react-router' ;

// redux
import {connect} from 'react-redux';
import {mapStateToProps,mapDispatchToProps} from '../../store.jsx' ;


class Header extends Component {
	pdMenu(){
		this.props.getMenu?
		this.props.setMenu(false):
		this.props.setMenu(true) ;
	}
	toCitys(){
		browserHistory.push('/citys')
	}
	toMine(){
		browserHistory.push('/mine')
	}
	render(){
		return (
			<header>
				<div id="nav_bth" onClick={this.pdMenu.bind(this)}>
					<img src="src/images/icon/我的订单.png"/>
				</div>

				<span className="title">
					{this.props.getHeaderName}
				</span>
				<div id="mine_bth" onClick={this.toMine.bind(this)}>
					<img src="src/images/icon/我的聚划算.png"/>
				</div>
				<div className="city" onClick={this.toCitys.bind(this)}>
					<span>{this.props.getCity}</span>
					<img src="src/images/icon/向下箭头.png"/>
				</div>
			</header>)
	}
}

export default connect(mapStateToProps,mapDispatchToProps)(Header)
